CREATE TABLE IF NOT EXISTS `quotes` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `author` INT,
    `sentence` VARCHAR(255),
     PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
INSERT INTO `quotes`(`author`, `sentence`) VALUES
    (7,'The man who passes the sentence should swing the sword.'),
    (7,'Winter is coming!'),
    (7,'I, Eddard of the house Stark, lord of Winterfell and warden of the North, sentence you to die.'),
    (7,'A madman sees what he sees.'),
    (7,'I grew up with soldiers. I learNed how to die a long time ago.'),
    (3,'If I fall, don''t bring me back.'),
    (3,'There is only one war that matters. The Great War. And it is here.'),
    (3,'Love is the death of duty.'),
    (3,'Everything before the word "but" is horseshit.'),
    (3,'The war is not over. And I promise you, friend, the true enemy won''t wait out the storm. He brings the storm.'),
    (5,'I hate the king more than any of them.'),
    (5,'No need to seize the last word, Lord Baelish. I''ll assume it was something clever.'),
    (4,'When people ask you what happeNed here, tell them the North remembers. Tell them winter came for House Frey.'),
    (4,'Nothing isn''t better or worse than anything. Nothing is just nothing.'),
    (4,'Leave one wolf alive and the sheep are never safe.'),
    (6,'We don''t have time for all this. The Night King has your dragon. He''s one of them now. The Wall has fallen. The dead march south.'),
    (9,'The things I do for love.'),
    (9,'Fighting bravely for a losing cause is admirable. Fighting for a winning cause is far more rewarding.'),
    (9,'Three victories don''t make you a conqueror.'),
    (9,'By what right does the wolf judge the lion?'),
    (15,'I have a tender spot in my heart for cripples, bastards and broken things.'),
    (15,'Never forget what you are. The rest of the world will not. Wear it like armour, and it can never be used to hurt you.'),
    (15,'The day will come when you think you are safe and happy, and your joy will turn to ashes in your mouth.'),
    (15,'That''s what I do: I drink and I know things.'),
    (15,'I am your son. I have always been your son.'),
    (15,'You love your children. It''s your one redeeming quality. That and your cheekbones.'),
    (15,'That bit of theatre will haunt our family for a generation.'),
    (15,'Love is more powerful than reason. We all know that.'),
    (15,'A Lannister always pays his debts.'),
    (15,'I know that our enemies hate each other almost as much as they hate us.'),
    (15,'Well, my brother has his sword, and I have my mind, and a mind needs books like a sword needs a whetstone.'),
    (15,'It''s not easy being drunk all the time. Everyone would do it, if it were easy.'),
    (15,'A ruler who kills those devoted to her is not a ruler who inspires devotion.'),
    (15,'Never forget what you are. The rest of the world will not. Wear it like armor, and it can never be used to hurt you.'),
    (15,'Everyone who makes a joke about a dwarf''s height thinks he''s the only person ever to make a joke about a dwarf''s height.'),
    (15,'No matter who you are, no matter how strong you are, sooner or later, you''ll face circumstances beyond your control.'),
    (15,'I''m a constant disappointment to my own father, and I have learNed to live with it.'),
    (10,'When you play the game of thrones, you win or you die. There is no middle ground.'),
    (10,'If you ever call me sister again, I''ll have you strangled in your sleep.'),
    (10,'If you want a whore, buy one. If you want a Queen, earn her.'),
    (10,'Tears aren''t a woman''s only weapon. The best one''s between your legs.'),
    (10,'The only way to keep your people loyal is to make certain they fear you more than they do the enemy.'),
    (10,'I want our baby to live. Don''t let me die, Jamie. Please don''t let me die.'),
    (10,'I don''t care about checking my worst impulses. I don''t care about making the world a better place. Hang the world.'),
    (43,'A lion does not concern himself with the opinion of sheep.'),
    (43,'Any man who must say ''I am the King'' is no true King.'),
    (43,'Every day that he remains a prisoner, the less our name commands respect.'),
    (43,'I need you to become the man you were always meant to be. Not next year, not tomorrow, now.'),
    (14,'Everyone is mine to torment.'),
    (1,'I am the dragon''s daughter, and I swear to you that those who would harm you will die screaming.'),
    (1,'He was no dragon. Fire cannot kill a dragon.'),
    (1,'All men must die, but we are not men.'),
    (36,'If you think this has a happy ending, you haven''t been paying attention.'),
    (35,'I''m the King, I get what I want. I never loved my brothers. Sad thing for a man to admit, but it''s true. You were the brother I chose.'),
    (13,'My sword is yours, in victory and defeat, from this day until my last day.'),
    (13,'It''s better to be cruel than weak.'),
    (2,'I was nothing at all. And when you''re nothing at all, there''s no reason to be afraid.'),
    (20,'The storms come and go, the big fish eat the little fish and I keep on paddling.'),
    (20,'Power resides where men believe it resides. It''s a trick, a shadow on the wall. And a very small man can cast a very large shadow.'),
    (24,'All I ever wanted was to fight for a lord I believed in. But the good lords are dead and the rest are monsters.'),
    (17,'A man with no motive is a man no one suspects. Always keep your foes confused.'),
    (17,'Chaos isn''t a pit. Chaos is a ladder.'),
    (17,'It doesn''t matter what we want. Once we get it, then we want something else.'),
    (17,'The fall breaks them. And some are given a chance to climb; they cling to the real or the gods or love.'),
    (17,'I have always found revenge to be the purest of motivations.'),
    (45,'Gingers are beautiful. We''ve been kissed by fire.'),
    (41,'The night is dark and full of terrors.'),
    (4,'Fear cuts deeper than swords.'),
    (51,'The world is overflowing with horrible things, but they’re all a tray of cakes next to death.'),
    (17,'It doesn’t matter what we want. Once we get it, then we want something else.'),
    (48,'Hodoooor !...'),
    (48,'HODOR !...'),
    (48,'hodor ?');
